export let CONST = {
  score: 0,
  highScore: 0,
  shootingPointx: 400,
  shootingPointy: 500,
  standbyPointX: 500,
  standbyPointY: 500,
  eggWidth: 50,
  eggHeight: 50,
  eggMapLength: 0,
  worldLeftBound: 140,
  worldRightBound: 640,
  worldWidth: 50 * 9,
  worldHeight: Infinity,
  texture: "egg_",
  frames: [
    "red",
    "blue",
    "green",
    "violet",
    "pink",
    "gray",
    "black",
    "orange",
    "yellow",
  ],
};
